/* Verilog module instantiation template generated by SCUBA Diamond_2.2_Production (93) */
/* Module Version: 5.5 */
/* Mon Aug 19 13:14:30 2013 */

/* parameterized module instance */
PH_DLY_FIFO __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .Empty( ), .Full( ));
