/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.8.0.115.3 */
/* Module Version: 5.7 */
/* Sun Feb 18 00:16:25 2018 */

/* parameterized module instance */
pll_pix2byte_YUV422_8bit_1lane __ (.CLKI( ), .RST( ), .CLKOP( ), 
    .CLKOS( ), .CLKOS2( ), .LOCK( ));
