/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.8.0.115.3 */
/* Module Version: 5.7 */
/* Mon Jan 22 11:07:12 2018 */

/* parameterized module instance */
pll_sony_block_cam_interface __ (.CLKI( ), .CLKOP( ), .CLKOS( ));
